---

- name: Create PostgreSQL database
  shell: "oc new-app --template=postgresql-ephemeral -p NAMESPACE=openshift -p POSTGRESQL_DATABASE="postgres" -p POSTGRESQL_USER=postgres -p POSTGRESQL_PASSWORD=postgres -n {{OCP_PROJECT}}"

- name: Create ConfigMap
  shell: "oc create configmap postgresql-config-map --from-file={{ role_path }}/files/provision_data.sh --from-file={{ role_path }}/files/wait_for_postgres.sh --from-file={{ role_path }}/files/provision_test_data.sql -n {{OCP_PROJECT}}"

- name: Attach ConfigMap
  shell: oc volume dc/postgresql --name=postgresql-config-volume --add -m /tmp/config-files -t configmap --configmap-name=postgresql-config-map -n {{OCP_PROJECT}}
