---

- name: Create ImageStream
  shell: "oc create -f {{ role_path }}/files/rhpam73-bc-cm-image-streams -n {{ OCP_PROJECT }}"
  when: rhpam_result is failed

- name: "Configure Business Central ImageStream"
  shell: "oc patch dc/rhpam7-rhpamcentr --type='json' -p '[{\"op\": \"replace\", \"path\": \"/spec/triggers/0/imageChangeParams/from/name\", \"value\": \"rhpam73-businesscentral-openshift-cm-showcase:1.0\"}]' -n {{ OCP_PROJECT }}"

- name: "Configure Business Central environment variables."
  shell: "oc set env dc/rhpam7-rhpamcentr JAVA_OPTS_APPEND=\"-Dorg.jbpm.casemgmt.showcase.url=/rhpam-case-mgmt-showcase -Dorg.kie.server.location=http://rhpam7-kieserver:8080/services/rest/server\" -n {{ OCP_PROJECT }}"
