---

- name: Set KIE_ADMIN Password
  shell: "oc set env dc/rhpam7-kieserver KIE_ADMIN_PWD=redhatpam1! -n {{ OCP_PROJECT }}"

- name: Set KIE_SERVER_CONTROLLER Password
  shell: "oc set env dc/rhpam7-kieserver KIE_SERVER_CONTROLLER_PWD=test1234! -n {{ OCP_PROJECT }}"

- name: Set KIE_SERVER Password
  shell: "oc set env dc/rhpam7-kieserver KIE_SERVER_PWD=test1234! -n {{ OCP_PROJECT }}"

# - name: Set RHPAMCENTR_MAVEN_REPO_PASSWORD Password
#   shell: "oc set env dc/rhpam7-kieserver RHPAMCENTR_MAVEN_REPO_PASSWORD=test1234! -n {{ OCP_PROJECT }}"
