---

#- name: Cancel running rollout
#  shell: "oc rollout cancel dc/rhpam7-rhpamcentr"

- name: Check if ImageStream exists
  shell: "oc get is/rhpam-kieserver-rhel8-cors -n {{OCP_PROJECT}}"
  register: is_result
  ignore_errors: true
  changed_when: false

- name: Create ImageStream
  shell: "oc create -f {{ role_path }}/files/rhpam75-ks-cors-image-streams.yml -n {{ OCP_PROJECT }}"
  when: is_result is failed

- name: "Configure KIE-Server ImageStream"
  shell: "oc patch dc/rhpam7-kieserver --type='json' -p '[{\"op\": \"replace\", \"path\": \"/spec/triggers/0/imageChangeParams/from/name\", \"value\": \"rhpam-kieserver-rhel8-cors:7.5.0\"}]' -n {{ OCP_PROJECT }}"
  when: is_result is failed

- name: "Configure KIE-Server ImageStream Namespace"
  shell: "oc patch dc/rhpam7-kieserver --type='json' -p '[{\"op\": \"replace\", \"path\": \"/spec/triggers/0/imageChangeParams/from/namespace\", \"value\": \"{{OCP_PROJECT}}\"}]' -n {{ OCP_PROJECT }}"
  when: is_result is failed

#- name: Trigger BC rollout
#  shell: "oc rollout latest dc/rhpam7-rhpamcentr"
